h=uicontrol('Style', 'slider',...
        'Min',0,'Max',1,'Value',0.01,...
        'Position', [400 20 120 20],...
    'Callback',{@su});
function a= su(h,event) %#ok<INUSL> 
    val =get(h,'Value');
   a=val
end